USE [master]
GO

/****** Object:  Database [WifiCheckIn]    Script Date: 2016/2/24 16:49:57 ******/
CREATE DATABASE [WifiCheckIn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WifiCheckIn', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WifiCheckIn.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WifiCheckIn_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WifiCheckIn_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WifiCheckIn] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WifiCheckIn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WifiCheckIn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WifiCheckIn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WifiCheckIn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WifiCheckIn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WifiCheckIn] SET ARITHABORT OFF 
GO

ALTER DATABASE [WifiCheckIn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WifiCheckIn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WifiCheckIn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WifiCheckIn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WifiCheckIn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WifiCheckIn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WifiCheckIn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WifiCheckIn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WifiCheckIn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WifiCheckIn] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WifiCheckIn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WifiCheckIn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WifiCheckIn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WifiCheckIn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WifiCheckIn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WifiCheckIn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WifiCheckIn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WifiCheckIn] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WifiCheckIn] SET  MULTI_USER 
GO

ALTER DATABASE [WifiCheckIn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WifiCheckIn] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WifiCheckIn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WifiCheckIn] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WifiCheckIn] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WifiCheckIn] SET  READ_WRITE 
GO


